version: '3.2'
services:
  sql-server-db:
    container_name: sql-server-pauli
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'pauli_password_xyz@secure123_to_change_later'
      ACCEPT_EULA: 'Y'